name: Angular front end build

on: 
 push:
  paths:
    - angular/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get all packages
      run: npm install && npm run build
      working-directory: ./angular

    - name: Publish generated content to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: angular/dist/pDFGenius # The folder the action should deploy.

    - name: Archive Angular Website Content
      uses: actions/upload-artifact@v1
      with:
          name: Angular-Website-Content
          path: angular/dist/pDFGenius
