name: Angular front end build

on: 
 push:
  paths:
    - angular/**

jobs:
  build:

    runs-on: ubuntu-latest
      

    steps:
    - uses: actions/checkout@v1
    - name: Get all packages
      run: npm install
      working-directory: ./angular

    - name: Build Angular site
      run: |
           npm run build
           ls -l ./dist/pDFGenius
      working-directory: ./angular

    - name: Publish generated content to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: angular/dist/pDFGenius # The folder the action should deploy.
