name: .NET Core - Built based on abp.io

on: 
 push:
   paths: 
     - aspnet-core/**

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: '3.1.100' # SDK Version to use.
      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: ./aspnet-core
      - name: Public ASP Net Web API Content
        uses: actions/upload-artifact@v1
        with:
          name: ASPNet-WebAPI
          path: aspnet-core

