name: .NET Core - Built based on abp.io

on: 
 push:
   paths: 
     - aspnet-core/**

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: '3.1.100' # SDK Version to use.
      - name: Build with dotnet
        run: dotnet build --configuration Release -o build
        working-directory: ./aspnet-core
      - name: Publish ASP Net Web API Content Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ASPNet-WebAPI
          path: aspnet-core/build
      - name: Package Nuget  
        run: dotnet pack --configuration Release
        working-directory: ./aspnet-core
      - name: Publish nuget
        run: |
           for f in "bin/Release/*.nupkg"
           do
             curl -vX PUT -u "${{ secrets.ACCESS_TOKEN }}" -F package=@$f https://nuget.pkg.github.com/edenprairie/
           done
        shell: bash
      
